# Generated by Django 2.2 on 2022-04-02 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='alerts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startsAt', models.DateTimeField(verbose_name='告警产生时间')),
                ('endsAt', models.DateTimeField(verbose_name='告警恢复时间')),
                ('instance', models.CharField(blank=True, max_length=50, verbose_name='实例')),
                ('alertname', models.CharField(max_length=100, verbose_name='告警名称')),
                ('status', models.CharField(blank=True, max_length=20, verbose_name='状态')),
                ('severity', models.CharField(blank=True, max_length=20, verbose_name='告警级别')),
                ('message', models.CharField(blank=True, max_length=1000, verbose_name='告警信息')),
                ('known', models.BooleanField(default=False, verbose_name='知悉')),
                ('memo', models.CharField(blank=True, max_length=50, verbose_name='知悉备注')),
            ],
            options={
                'verbose_name': '告警日志',
                'verbose_name_plural': '告警日志',
                'db_table': 'alerts',
            },
        ),
        migrations.CreateModel(
            name='production',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startsAt', models.DateTimeField(verbose_name='告警产生时间')),
                ('endsAt', models.DateTimeField(verbose_name='告警恢复时间')),
                ('instance', models.CharField(blank=True, max_length=50, verbose_name='实例')),
                ('alertname', models.CharField(max_length=100, verbose_name='告警名称')),
                ('status', models.CharField(blank=True, max_length=20, verbose_name='状态')),
                ('severity', models.CharField(blank=True, max_length=20, verbose_name='告警级别')),
                ('message', models.CharField(blank=True, max_length=1000, verbose_name='告警信息')),
                ('known', models.BooleanField(default=False, verbose_name='知悉')),
            ],
            options={
                'verbose_name': '告警统计',
                'verbose_name_plural': '告警统计',
                'db_table': 'production',
            },
        ),
    ]
