# Generated by Django 2.2 on 2022-04-02 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='alarmuser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=20, verbose_name='告警人')),
                ('useremail', models.EmailField(blank=True, max_length=20, verbose_name='告警邮件')),
                ('group', models.CharField(blank=True, max_length=20, verbose_name='分组')),
            ],
            options={
                'verbose_name': '告警人配置',
                'verbose_name_plural': '告警人配置',
                'db_table': 'alarmuser',
            },
        ),
    ]
